### PR TITLE
Update artifactoryonline URLs

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @sschaef

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
Let me know if it solves your build problems.

**Comment by lrytz** [comment]
It definitely helped, the [re-build i triggered](https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/1289/console) failed for a different reason.

**Comment by lrytz** [comment]
for the record, that failure was spurious, [a re-build succeeded](https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/1290/).

**Pull request merged**
