### PR TITLE
Update publish config for Scala 2.11.6-SNAPSHOT (for incremental compiler)

### PR DESCRIPTION
**Pull request by adriaanm**
Companion to https://github.com/scala/scala/pull/4247

review by @skyluc

### CODE REVIEW

**Comment by dragos** [comment]
does this need to wait for the Scala PR to be merged?

**Comment by adriaanm** [comment]
If prefer to merge this first because the Scala pr can't go green otherwise.

**Comment by dragos** [comment]
Ok, I'll bump versions. BTW, the file that's run during pr validation is `validator.conf`, this file is used only to publish an incremental compiler for the given Scala versions.

**Comment by dragos** [comment]
@adriaanm it seems there are no 2.11.6-SNAPSHOT builds yet, so we can't build sbt on 2.11.6-SNAPSHOT.. 

I think it's simpler to push 2.11.6-SNAPSHOT first, and then bump the IDE build.

**Comment by adriaanm** [comment]
Ok, I based it on the other PR that had a relevant-sounding title: https://github.com/scala-ide/uber-build/pull/66

**Comment by adriaanm** [comment]
I'm on hotel wifi right now, so it's taking a while, but I'm seeing a lot of red in the pr-scala-integrate-ide build history.

**Comment by adriaanm** [comment]
I have to run -- maybe coordinate with someone in CET? /cc @grek, @lrytz

**Comment by lrytz** [comment]
Latest pr-scala-integrate-ide succeeded (https://scala-webapps.epfl.ch/jenkins/job/pr-scala/9526/BuildGraph/), after https://github.com/typesafehub/sbt-republish/pull/10

**Comment by adriaanm** [comment]
Cool! Let's merge the Scala or that bumps the snapshot version.

**Pull request closed without merging**
